version: 2
jobs:
	build:
		machine:
			image: ubuntu-1604:201903-01
		steps:
			- checkout
			- run g++ *.cpp
	print:
		machine:
			image: ubuntu-1604:201903-01
		steps:
			- checkout
			- run cat main.cpp
workflows:
	version: 2
	build_and_print:
		jobs:
			- build
			- print:
				requires:
					- build
