version: 2
jobs:
  build:
    machine:
    working_directory: ~/teszt/Test
    steps:
      - checkout:
          path: ~/teszt
      - run: 'g++ *.h *.cpp -std=c++11'
    persist_to_workspace:
      paths: a.out
  test:
    machine:
    steps:
      - run: './a.out < Test/test.txt > Test/out.txt'
      - run: 'diff Test/out.txt Test/testresult.txt'

      - store_artifacts:
          path: a.out
          destination: Binary file
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
