orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run: 'g++ -std=c++11 *.cpp *.h'
workflows:
  version: 2
  workflow:
    jobs:
    - build
