version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/SZE-MoSzE-2019-Tristania/Tests
    steps:
      - checkout:
          path: ~/SZE-MoSzE-2019-Tristania
      - run: 'g++ *.cpp -std=c++11'
    persist_to_workspace:
      paths: a.out
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: './a.out < Tests/test.txt > Tests/out.txt'
      - run: 'diff Tests/out.txt Tests/testresult.txt'

      - store_artifacts:
          path: a.out
          destination: Binary file
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
