orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run: 'g++ -std=c++11 *.cpp *.h'
  test:
    executor: machine
    steps:
      - run: './a.out < Test/test.txt > Test/out.txt'
      - run: 'diff Test/out.txt Test/testresult.txt'

      - store_artifacts:
          path: a.out
          destination: Binary file

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
