  version: 2.1
  jobs:
    build:
      machine: 
        image: ubuntu-1604:201903-01 # the primary container, where your job's commands are run
      working_directory: ~/teszt
      steps:
        - checkout # check out the code in the project directory
        - run: make -f makefile #build the project
        -  run: pwd
        - persist_to_workspace:
            root: ~/home/circleci/teszt
            paths:
              - terminal
    output:
      machine:
         image: ubuntu-1604:201903-01
      steps:
         - attach_workspace:
            at: ~/
         - run: ./terminal < input
    difference:
      machine:
         image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/home/circleci/teszt
        - run: ./terminal < input > output
        - run: diff output outputTest
  workflows:
    version: 2.1
    build_print_diff:
      jobs:
        - build
        - output:
           requires:
             - build
        - difference:
           requires:
             - build
