orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucu
            bundle exec cucu --format junit --out ~/cucu/junit.xml
          when: always
      - store_test_results:
          path: ~/cucu
      - store_artifacts:
          path: ~/cucu

workflows:
  version: 2
  workflow:
    jobs:
    - build
