version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01 
    steps:
      - checkout
      - run: 
          name: Build
          command: make -f makefile
      - run:
          name: Output
          command: ./terminal < input
      - run:
          name: Diff
          command: ./terminal < input > output && diff output outputTest
          
