version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/teszt/Test
    steps:
      - checkout
      - run: 'g++ -std=c++11 *.cpp *.h'
    persist_to_workspace:
      paths: a.out
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: './a.out < Test/test.txt >'
      - run: '< Test/test.txt > Test/out.txt'
      - run: 'diff Test/out.txt Test/tresult.txt'
      
      - store_artifacts:
          path: a.out
          destination: Binary file

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
