orbs:
  win: circleci/windows@1.0.0

version: 2.1
jobs:
  build:
    machine
    steps:
      << checkout
      - run: 'g++ -std=c++11 *.cpp *.h'
  test:
      machine
      steps:
      - run: './a.out < Test/test.txt > Test/out.txt'
      - run: 'diff Test/out.txt Test/testresult.txt'
      
      - store_artifacts:
          path: a.out
          destination: Binary file

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
