orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: machine
    working_directory: ~/teszt/Test
    steps:
      - checkout
      - run: 'g++ -std=c++11 *.cpp *.h'
    test:
      executor: machine
      steps:
      - run: './a.out < Tests/test.txt > Tests/out.txt'
      - run: 'diff Tests/out.txt Tests/testresult.txt'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
